language: node_js
node_js:
  - 9

branches:
  only:
    - travis

after_success:
      - find dist -type f -exec curl --ftp-create-dirs -T {} ftp://mirexda2.beget.tech --user ${SFTP_USER}:${SFTP_PASSWORD} \;