language: node_js
node_js:
  - 9

branches:
  only:
    - travis

after_success:
      - cd dist
      - find . -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://mirexda2.beget.tech --user ${SFTP_USER}:${SFTP_PASSWORD} \;